Script started on 2016年03月14日 (週一) 00時04分25秒
]0;H34041092@2015cpp: ~/LionH34041092@2015cpp:~/Lion$ whoami;pwd
H34041092
/home/H34041092/Lion
]0;H34041092@2015cpp: ~/LionH34041092@2015cpp:~/Lion$ whoami;pwdgit clone https://github.com/EvanChenPrograming/lab1.giit[A]0;H34041092@2015cpp: ~/LionH34041092@2015cpp:~/Lion$ [C[C[C[C[Config -l[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Clone https://github.com/EvanChenPrograming/lab1.giit[A]0;H34041092@2015cpp: ~/LionH34041092@2015cpp:~/Lion$ [C[C[C[C[Config -l[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C
user.name=EvanChen
user.email=H34041092@ncku.edu.tw
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
]0;H34041092@2015cpp: ~/LionH34041092@2015cpp:~/Lion$ git config -l[3Pwhoami;pwdgit clone https://github.com/EvanChenPrograming/lab1.giit
Cloning into 'lab1'...
remote: Counting objects: 12, done.[K
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12[K
Unpacking objects:   8% (1/12)   Unpacking objects:  16% (2/12)   Unpacking objects:  25% (3/12)   Unpacking objects:  33% (4/12)   Unpacking objects:  41% (5/12)   Unpacking objects:  50% (6/12)   Unpacking objects:  58% (7/12)   Unpacking objects:  66% (8/12)   Unpacking objects:  75% (9/12)   Unpacking objects:  83% (10/12)   Unpacking objects:  91% (11/12)   Unpacking objects: 100% (12/12)   Unpacking objects: 100% (12/12), done.
]0;H34041092@2015cpp: ~/LionH34041092@2015cpp:~/Lion$ exit

Script done on 2016年03月14日 (週一) 00時04分53秒
